project:
  type: website  
  output-dir: "docs"

execute:
  freeze: auto
  jupyter:
    python: /home/janhsc/Documents/projects/JHSchlegel.github.io/.venv/bin/python

website:
  title: "Jan Schlegel"
  favicon: logo.png
  navbar:
    pinned: true
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/jan-heinrich-schlegel/
      - icon: github
        href: https://github.com/JHSchlegel

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    css: styles.css
    include-in-header:
      - text: |
          <meta name="color-scheme" content="dark light">
